"use client"

import type React from "react"
import { createContext, useContext, useState, type ReactNode } from "react"

interface LanguageContextType {
  language: "en" | "hi"
  toggleLanguage: () => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Header & Branding
    swasthyaai: "SwasthyaAI",
    medisense: "SwasthyaAI",
    tagline: "Your Intelligent Health Companion",
    home: "Home",
    login: "Login",
    register: "Register",
    logout: "Logout",
    emergency: "Emergency",
    dashboard: "Dashboard",
    medications: "Medications",
    profile: "Profile",
    view_profile: "View Profile",
    mediaware: "MediAware",
    education: "MediAware",
    medicollab: "MediCollab",
    contact: "Contact Us",
    mediconnect: "MediConnect",
    symptom_checker: "Symptom Checker",

    // Home Page
    hero_title: "Your Health Journey Starts Here",
    hero_subtitle:
      "Get instant AI-powered health insights, personalized recommendations, and access to healthcare professionals when you need them most.",
    check_symptoms: "Check Symptoms Now",
    view_dashboard: "Register & Get Started",
    start_journey: "Start Your Health Journey",

    // Features
    features_title: "Why Choose SwasthyaAI?",
    ai_diagnosis: "AI-Powered Diagnosis",
    ai_diagnosis_desc: "Advanced AI analyzes your symptoms and provides accurate health insights",
    expert_care: "24/7 Expert Care",
    expert_care_desc: "Connect with healthcare professionals anytime, anywhere",
    personal_tracking: "Personal Health Tracking",
    personal_tracking_desc: "Monitor your health metrics and medication schedules",
    emergency_support: "Emergency Support",
    emergency_support_desc: "Instant access to emergency services and nearby hospitals",

    // Dashboard
    welcome_back: "Welcome back",
    welcome_new_user: "Welcome to SwasthyaAI!",
    complete_profile: "Complete your health profile to get personalized insights",
    health_overview: "Here's your health overview for today",
    health_metrics: "Health Metrics",
    recent_activities: "Recent Activities",
    quick_actions: "Quick Actions",
    profile_summary: "Profile Summary",
    health_trends: "Health Trends",
    bmi: "BMI",
    weight: "Weight",
    height: "Height",
    blood_pressure: "Blood Pressure",
    heart_rate: "Heart Rate",
    body_temperature: "Body Temperature",
    oxygen_saturation: "Oxygen Saturation",
    edit_profile: "Edit Profile",
    save_changes: "Save Changes",
    cancel: "Cancel",

    // Health Status
    underweight: "Underweight",
    normal_weight: "Normal Weight",
    overweight: "Overweight",
    obese: "Obese",
    normal: "Normal",
    high: "High",
    low: "Low",
    excellent: "Excellent",
    good: "Good",
    fair: "Fair",
    poor: "Poor",

    // Forms
    full_name: "Full Name",
    email_address: "Email Address",
    phone_number: "Phone Number",
    age: "Age",
    blood_group: "Blood Group",
    weight_kg: "Weight (kg)",
    height_cm: "Height (cm)",
    systolic_bp: "Systolic BP",
    diastolic_bp: "Diastolic BP",
    heart_rate_bpm: "Heart Rate (BPM)",
    temperature_f: "Temperature (°F)",
    oxygen_percent: "Oxygen Saturation (%)",
    medical_history: "Medical History",
    emergency_contact: "Emergency Contact",
    contact_name: "Contact Name",
    contact_phone: "Contact Phone",
    relationship: "Relationship",

    // Common
    loading: "Loading...",
    submit: "Submit",
    save: "Save",
    next: "Next",
    back: "Back",
    close: "Close",
    search: "Search",
    filter: "Filter",
    all: "All",
    read_more: "Read More",
    book_appointment: "Book Appointment",
    schedule_consultation: "Schedule Consultation",
    get_personalized_help: "Get Personalized Help",
    years: "years",
    kg: "kg",
    cm: "cm",
    bpm: "BPM",
    mmhg: "mmHg",
    fahrenheit: "°F",
    percent: "%",

    // Symptom Checker
    ai_symptom_checker: "AI Symptom Checker",
    powered_by_ai: "Powered by advanced AI for personalized health insights",
    describe_symptoms: "Describe your symptoms",
    send_message: "Send Message",
    ai_assistant_online: "AI Assistant Online",
    medical_disclaimer: "Medical Disclaimer",
    disclaimer_text:
      "This AI assistant provides general health information only and should not replace professional medical advice. For emergencies, call emergency services immediately. Always consult healthcare providers for diagnosis and treatment.",
    immediate_help: "Immediate help & hospital locator",
    health_education: "Health Education",
    learn_health_topics: "Learn about health topics",
    register_for_more: "Register for More Features",
    get_personalized_insights: "Get Personalized Health Insights",
    unlock_features:
      "Register to unlock personalized health tracking, medication reminders, and access to your complete health dashboard.",

    // Sample questions
    persistent_headache: "Persistent headache",
    chest_discomfort: "Chest discomfort",
    fever_body_aches: "Fever and body aches",

    // Error messages
    access_denied: "Access Denied",
    login_required: "Please log in to view your dashboard",
    invalid_credentials: "Invalid email or password. Please try again.",
    user_exists: "User with this email already exists",
    password_mismatch: "Passwords do not match",
    password_length: "Password must be at least 6 characters long",
    required_field: "This field is required",

    // Success messages
    profile_updated: "Profile updated successfully",
    registration_success: "Registration successful! Welcome to SwasthyaAI.",
    login_success: "Login successful! Welcome back.",

    // Emergency Page
    emergency_support_title: "Emergency Support",
    immediate_help_desc: "Immediate help when you need it most",
    emergency_numbers: "Emergency Numbers",
    emergency_services: "Emergency Services",
    all_emergency_services: "All emergency services",
    ambulance: "Ambulance",
    medical_emergency: "Medical emergency",
    fire_department: "Fire Department",
    fire_emergency: "Fire emergency",
    police: "Police",
    police_emergency: "Police emergency",
    disaster_management: "Disaster Management",
    natural_disasters: "Natural disasters",
    find_nearby_hospitals: "Find Nearby Hospitals",
    locate_hospitals_desc: "Locate the nearest hospitals and get directions immediately",
    find_navigate_hospitals: "Find & Navigate to Hospitals",
    your_medical_information: "Your Medical Information",
    name: "Name",
    blood_group_info: "Blood Group",
    emergency_contact_info: "Emergency Contact",
    first_aid_quick_reference: "First Aid Quick Reference",
    cpr_full: "CPR (Cardiopulmonary Resuscitation)",
    choking: "Choking",
    severe_bleeding: "Severe Bleeding",
    burns: "Burns",
    fractures: "Fractures",
    seizures: "Seizures",
    stroke_fast: "Stroke (FAST)",
    allergic_reactions: "Allergic Reactions",
    click_step_by_step: "Click for step-by-step guide",
    back_to_all_guides: "← Back to All Guides",
    important: "Important",
    remember_disclaimer:
      "Remember: These are basic first aid guidelines. Always call emergency services (112/108) for serious injuries or if you're unsure about the severity of the situation.",

    // Contact Page
    contact_us: "Contact Us",
    contact_desc: "We're here to help! Reach out to us for any questions, support, or collaboration opportunities.",
    get_in_touch: "Get in Touch",
    phone: "Phone",
    email: "Email",
    address: "Address",
    support_hours: "Support Hours",
    emergency_support_24_7: "24/7 Emergency Support",
    general_inquiries: "General inquiries: 9 AM - 6 PM IST",
    our_response_time: "Our Response Time",
    general: "General",
    send_us_message: "Send us a Message",
    message_success: "Thank you for your message! We'll get back to you soon.",
    message_error: "Sorry, there was an error sending your message. Please try again.",
    purpose: "Purpose",
    select_purpose: "Select purpose",
    general_inquiry: "General Inquiry",
    technical_support: "Technical Support",
    medical_consultation: "Medical Consultation",
    partnership_collaboration: "Partnership/Collaboration",
    feedback_suggestions: "Feedback/Suggestions",
    bug_report: "Bug Report",
    message: "Message",
    message_placeholder: "Please describe your inquiry or message in detail...",
    communication_consent: "I agree to receive communications from SwasthyaAI regarding my inquiry",
    sending: "Sending...",
    send_message_btn: "Send Message",
    frequently_asked_questions: "Frequently Asked Questions",
    ai_accuracy_question: "How accurate is the AI symptom checker?",
    ai_accuracy_answer:
      "Our AI is trained on extensive medical data and provides guidance based on symptoms, but it should not replace professional medical advice.",
    data_security_question: "Is my health data secure?",
    data_security_answer:
      "Yes, we use industry-standard encryption and comply with healthcare data protection regulations to keep your information secure.",
    book_appointments_question: "Can I book appointments with doctors?",
    book_appointments_answer:
      "Yes, through our MediConnect feature, you can schedule video consultations with verified healthcare professionals.",
    emergency_services_question: "Do you provide emergency services?",
    emergency_services_answer:
      "We provide emergency support tools including hospital locators and first aid guides, but for immediate emergencies, call 112.",

    // Medications Page
    smart_medication_tracker: "Smart Medication Tracker",
    medication_tracker_desc: "Stay on track with your medications and build healthy habits",
    add_medication: "Add Medication",
    total_medications: "Total Medications",
    taken_today: "Taken Today",
    adherence_rate: "Adherence Rate",
    longest_streak: "Longest Streak",
    todays_medications: "Today's Medications",
    dosage: "Dosage",
    frequency: "Frequency",
    times: "Times",
    streak: "Streak",
    days: "days",
    this_week: "This week",
    mark_taken: "Mark Taken",
    completed: "Completed",
    achievements: "Achievements",
    seven_day_streak: "7-Day Streak",
    unlocked: "Unlocked!",
    perfect_week: "Perfect Week",
    perfect_week_desc: "100% adherence for 7 days",
    thirty_day_champion: "30-Day Champion",
    days_to_go: "days to go",
    upcoming_reminders: "Upcoming Reminders",
    due_at: "Due at",
    this_month: "This Month",
    days_100_adherence: "Days with 100% adherence",
    missed_doses: "Missed doses",
    average_adherence: "Average adherence",
    add_new_medication: "Add New Medication",
    medication_name: "Medication Name",
    medication_name_placeholder: "Enter medication name",
    dosage_placeholder: "e.g., 500mg, 1 tablet",
    once_daily: "Once daily",
    twice_daily: "Twice daily",
    three_times_daily: "Three times daily",
    as_needed: "As needed",
    instructions: "Instructions",
    instructions_placeholder: "Special instructions...",

    // Additional keys for other pages
    expert_consultations: "Expert Consultations",
    connect_with_doctors:
      "Connect with verified healthcare professionals for urgent consultations via video call, voice call, or text chat.",
    for_life_threatening: "For Life-Threatening Emergencies",
    call_emergency:
      "Call 112 or 108 immediately. This service is for non-emergency consultations and medical guidance.",
    choose_healthcare_professional: "Choose Your Healthcare Professional",
    experience: "Experience",
    rating: "Rating",
    languages: "Languages",
    available: "Available",
    consultation_fee: "Consultation Fee",
    continue_with: "Continue with",
    patient_information: "Patient Information",
    patient_name: "Patient Name",
    gender: "Gender",
    select_gender: "Select gender",
    male: "Male",
    female: "Female",
    other: "Other",
    consultation_type: "Consultation Type",
    video_call: "Video Call",
    voice_call: "Voice Call",
    text_chat: "Text Chat",
    face_to_face_consultation: "Face-to-face consultation via video call",
    audio_consultation: "Audio consultation over phone call",
    text_based_consultation: "Text-based consultation and guidance",
    urgency_level: "Urgency Level",
    normal_urgency: "Normal (within 24-48 hours)",
    urgent: "Urgent (within 2-4 hours)",
    very_urgent: "Very Urgent (within 1 hour)",
    current_symptoms: "Current Symptoms / Health Concerns",
    describe_symptoms_placeholder: "Please describe your symptoms, concerns, or reason for consultation...",
    relevant_medical_history: "Relevant Medical History",
    medical_history_placeholder: "Any relevant medical history, current medications, allergies, etc.",
    schedule_appointment: "Schedule Appointment",
    preferred_date: "Preferred Date",
    preferred_time: "Preferred Time",
    select_time: "Select time",
    appointment_summary: "Appointment Summary",
    doctor: "Doctor",
    specialty: "Specialty",
    patient: "Patient",
    urgency: "Urgency",
    terms_agreement:
      "I agree to the terms and conditions and understand that this consultation fee is non-refundable. I also consent to the recording of this session for quality and training purposes.",
    booking: "Booking...",
    confirm_appointment: "Confirm Appointment",
    appointment_confirmed: "Appointment Confirmed!",
    consultation_scheduled:
      "Your consultation has been scheduled successfully. You will receive a confirmation email with meeting details shortly.",
    date: "Date",
    time: "Time",
    type: "Type",
    fee: "Fee",
    back_to_home: "Back to Home",

    // Education/MediAware Page
    health_education_hub: "Health Education Hub",
    health_education_desc:
      "Explore comprehensive health resources, expert articles, and educational videos to empower your wellness journey.",
    search_placeholder: "Search articles, videos, and health topics...",
    all_content: "All Content",
    articles_only: "Articles Only",
    videos_only: "Videos Only",
    all_categories: "All Categories",
    heart_health: "Heart Health",
    mental_health: "Mental Health",
    prevention: "Prevention",
    fitness_nutrition: "Fitness & Nutrition",
    emergency_care: "Emergency Care",
    chronic_diseases: "Chronic Diseases",
    article: "Article",
    video: "Video",
    watch_video: "Watch Video",
    no_content_found: "No content found",
    adjust_search_filters: "Try adjusting your search terms or filters to find relevant health content.",
    need_personalized_guidance: "Need Personalized Health Guidance?",
    personalized_guidance_desc:
      "Connect with our AI-powered symptom checker or book a consultation with healthcare experts.",
    try_symptom_checker: "Try Symptom Checker",
    book_consultation: "Book Consultation",

    // Profile Page
    personal_information: "Personal Information",
    medical_information: "Medical Information",
    no_medical_conditions: "No medical conditions reported",
    privacy_security: "Privacy & Security",
    two_factor_auth: "Two-Factor Authentication",
    two_factor_desc: "Add an extra layer of security to your account",
    enable: "Enable",
    data_export: "Data Export",
    data_export_desc: "Download a copy of your health data",
    export: "Export",
    delete_account: "Delete Account",
    delete_account_desc: "Permanently delete your account and all data",
    delete: "Delete",

    // MediCollab Page
    partner_with_us: "Partner With Us",
    collaboration_mission_desc:
      "Join our mission to make quality healthcare accessible to everyone. Together, we can create a healthier India through collaboration, innovation, and shared commitment to wellness.",
    our_collaboration_mission: "Our Collaboration Mission",
    collaboration_mission_text:
      "SwasthyaAI believes in the power of partnerships to transform healthcare delivery. We're building an ecosystem where technology, expertise, and compassion come together to serve communities across India.",
    community_impact: "Community Impact",
    community_impact_desc: "Reaching underserved communities with quality healthcare",
    shared_values: "Shared Values",
    shared_values_desc: "Commitment to accessible, affordable, and quality healthcare",
    mutual_growth: "Mutual Growth",
    mutual_growth_desc: "Creating value for all stakeholders in the healthcare ecosystem",
    collaboration_opportunities: "Collaboration Opportunities",
    ngos_nonprofits: "NGOs & Non-Profits",
    ngo_description:
      "Partner with us to organize health camps, blood donation drives, and community wellness programs.",
    individual_ambassadors: "Individual Ambassadors",
    ambassador_description: "Become a SwasthyaAI ambassador in your community and help spread health awareness.",
    hospitals_clinics: "Hospitals & Clinics",
    hospital_description: "Join our network to provide quality healthcare services and reach more patients.",
    healthcare_professionals: "Healthcare Professionals",
    doctor_description: "Collaborate with us to provide expert medical guidance and expand your practice.",
    corporate_partners: "Corporate Partners",
    corporate_description:
      "Partner with us for employee wellness programs and corporate social responsibility initiatives.",
    academic_institutions: "Academic Institutions",
    academic_description: "Collaborate on research, education, and training programs to advance healthcare knowledge.",
    collaboration_opportunities_list: "Collaboration Opportunities:",
    benefits_recognition: "Benefits & Recognition:",
    success_stories: "Success Stories",
    rural_health_initiative: "Rural Health Initiative",
    rural_health_desc:
      "Partnered with 15 NGOs to conduct health camps in 50+ villages, screening over 10,000 people and providing free medications.",
    people_served: "People Served",
    ambassador_network: "Ambassador Network",
    ambassador_network_desc:
      "Trained 200+ community ambassadors who have conducted health awareness sessions reaching 25,000+ individuals.",
    active_ambassadors: "Active Ambassadors",
    hospital_network: "Hospital Network",
    hospital_network_desc:
      "Connected 100+ hospitals and clinics to our platform, enabling 50,000+ telemedicine consultations.",
    partner_hospitals: "Partner Hospitals",
    ready_to_collaborate: "Ready to Collaborate?",
    partnership_form_desc:
      "Fill out the form below and our partnership team will get in touch with you within 48 hours.",
    organization_representative: "Full Name / Organization Representative",
    organization_name: "Organization Name",
    organization_placeholder: "Enter organization name (if applicable)",
    collaboration_category: "Collaboration Category",
    select_category: "Select category",
    ngo_nonprofit: "NGO / Non-Profit",
    individual_ambassador: "Individual Ambassador",
    hospital_clinic: "Hospital / Clinic",
    healthcare_professional: "Healthcare Professional",
    corporate_partner: "Corporate Partner",
    academic_institution: "Academic Institution",
    location_city_state: "Location (City, State)",
    relevant_experience: "Relevant Experience / Background",
    experience_placeholder: "Briefly describe your relevant experience or background...",
    collaboration_ideas: "How would you like to collaborate with us?",
    collaboration_placeholder:
      "Please describe your collaboration ideas, goals, and how you can contribute to our mission...",
    consent_agreement:
      "I agree to be contacted by SwasthyaAI regarding collaboration opportunities and understand that my information will be used in accordance with the privacy policy.",
    submitting: "Submitting...",
    submit_collaboration_request: "Submit Collaboration Request",
    have_questions: "Have Questions?",
    partnership_team_help: "Our partnership team is here to help you explore collaboration opportunities.",
    
    // Stats
    happy_users: "Happy Users",
    healthcare_partners: "Healthcare Partners",
    support_available: "Support Available",
    uptime: "Uptime",

    // Testimonials
    software_engineer: "Software Engineer",
    general_physician: "General Physician",
    teacher: "Teacher",
    testimonial_priya: "SwasthyaAI helped me understand my symptoms and connected me with the right doctor. The AI diagnosis was incredibly accurate!",
    testimonial_rajesh: "As a healthcare professional, I appreciate how MediSense educates patients and helps them make informed decisions about their health.",
    testimonial_amit: "The emergency features saved my father's life. Quick access to nearby hospitals and first aid information is invaluable.",

    // Platform Description
    platform_description: "Our AI-powered platform combines cutting-edge technology with human expertise to provide comprehensive healthcare support.",

    // How It Works
    how_it_works: "How SwasthyaAI Works",
    simple_steps: "Simple steps to better health management",
    describe_symptoms_step: "Describe Your Symptoms",
    describe_symptoms_desc: "Tell our AI about your health concerns in natural language",
    get_ai_analysis: "Get AI Analysis",
    get_ai_analysis_desc: "Receive personalized health insights and recommendations",
    connect_with_experts: "Connect with Experts",
    connect_with_experts_desc: "Connect with healthcare professionals when needed",

    // Testimonials Section
    what_users_say: "What Our Users Say",
    trusted_by_users: "Trusted by thousands of users across India",

    // CTA Section
    ready_to_transform: "Ready to Transform Your Health Journey?",
    join_thousands: "Join thousands of users who trust SwasthyaAI for their healthcare needs",
  
  },
  hi: {
    // Header & Branding
    swasthyaai: "स्वस्थ्यAI",
    medisense: "स्वस्थ्यAI",
    tagline: "आपका बुद्धिमान स्वास्थ्य साथी",
    home: "होम",
    login: "लॉगिन",
    register: "रजिस्टर",
    logout: "लॉगआउट",
    emergency: "आपातकालीन",
    dashboard: "डैशबोर्ड",
    medications: "दवाइयां",
    profile: "प्रोफाइल",
    view_profile: "प्रोफाइल देखें",
    mediaware: "मेडीअवेयर",
    education: "मेडीअवेयर",
    medicollab: "मेडीकोलैब",
    contact: "संपर्क करें",
    mediconnect: "मेडीकनेक्ट",
    symptom_checker: "लक्षण जांचकर्ता",

    // Home Page
    hero_title: "आपकी स्वास्थ्य यात्रा यहां से शुरू होती है",
    hero_subtitle: "तत्काल AI-संचालित स्वास्थ्य अंतर्दृष्टि, व्यक्तिगत सिफारिशें, और जब आपको सबसे ज्यादा जरूरत हो तब स्वास्थ्य पेशेवरों तक पहुंच प्राप्त करें।",
    check_symptoms: "अभी लक्षण जांचें",
    view_dashboard: "रजिस्टर करें और शुरू करें",
    start_journey: "अपनी स्वास्थ्य यात्रा शुरू करें",

    // Features
    features_title: "स्वस्थ्यAI को क्यों चुनें?",
    ai_diagnosis: "AI-संचालित निदान",
    ai_diagnosis_desc: "उन्नत AI आपके लक्षणों का विश्लेषण करता है और सटीक स्वास्थ्य अंतर्दृष्टि प्रदान करता है",
    expert_care: "24/7 विशेषज्ञ देखभाल",
    expert_care_desc: "कभी भी, कहीं भी स्वास्थ्य पेशेवरों से जुड़ें",
    personal_tracking: "व्यक्तिगत स्वास्थ्य ट्रैकिंग",
    personal_tracking_desc: "अपने स्वास्थ्य मेट्रिक्स और दवा शेड्यूल की निगरानी करें",
    emergency_support: "आपातकालीन सहायता",
    emergency_support_desc: "आपातकालीन सेवाओं और पास के अस्पतालों तक तत्काल पहुंच",

    // Dashboard
    welcome_back: "वापसी पर स्वागत है",
    welcome_new_user: "स्वस्थ्यAI में आपका स्वागत है!",
    complete_profile: "व्यक्तिगत अंतर्दृष्टि प्राप्त करने के लिए अपनी स्वास्थ्य प्रोफाइल पूरी करें",
    health_overview: "आज के लिए आपका स्वास्थ्य अवलोकन",
    health_metrics: "स्वास्थ्य मेट्रिक्स",
    recent_activities: "हाल की गतिविधियां",
    quick_actions: "त्वरित कार्य",
    profile_summary: "प्रोफाइल सारांश",
    health_trends: "स्वास्थ्य रुझान",
    bmi: "बीएमआई",
    weight: "वजन",
    height: "ऊंचाई",
    blood_pressure: "रक्तचाप",
    heart_rate: "हृदय गति",
    body_temperature: "शरीर का तापमान",
    oxygen_saturation: "ऑक्सीजन संतृप्ति",
    edit_profile: "प्रोफाइल संपादित करें",
    save_changes: "परिवर्तन सहेजें",
    cancel: "रद्द करें",

    // Health Status
    underweight: "कम वजन",
    normal_weight: "सामान्य वजन",
    overweight: "अधिक वजन",
    obese: "मोटापा",
    normal: "सामान्य",
    high: "उच्च",
    low: "कम",
    excellent: "उत्कृष्ट",
    good: "अच्छा",
    fair: "सामान्य",
    poor: "खराब",

    // Forms
    full_name: "पूरा नाम",
    email_address: "ईमेल पता",
    phone_number: "फोन नंबर",
    age: "उम्र",
    blood_group: "रक्त समूह",
    weight_kg: "वजन (किग्रा)",
    height_cm: "ऊंचाई (सेमी)",
    systolic_bp: "सिस्टोलिक बीपी",
    diastolic_bp: "डायस्टोलिक बीपी",
    heart_rate_bpm: "हृदय गति (बीपीएम)",
    temperature_f: "तापमान (°F)",
    oxygen_percent: "ऑक्सीजन संतृप्ति (%)",
    medical_history: "चिकित्सा इतिहास",
    emergency_contact: "आपातकालीन संपर्क",
    contact_name: "संपर्क नाम",
    contact_phone: "संपर्क फोन",
    relationship: "रिश्ता",

    // Common
    loading: "लोड हो रहा है...",
    submit: "जमा करें",
    save: "सेव करें",
    next: "अगला",
    back: "वापस",
    close: "बंद करें",
    search: "खोजें",
    filter: "फिल्टर",
    all: "सभी",
    read_more: "और पढ़ें",
    book_appointment: "अपॉइंटमेंट बुक करें",
    schedule_consultation: "परामर्श शेड्यूल करें",
    get_personalized_help: "व्यक्तिगत सहायता प्राप्त करें",
    years: "वर्ष",
    kg: "किग्रा",
    cm: "सेमी",
    bpm: "बीपीएम",
    mmhg: "mmHg",
    fahrenheit: "°F",
    percent: "%",

    // Symptom Checker
    ai_symptom_checker: "AI लक्षण जांचकर्ता",
    powered_by_ai: "व्यक्तिगत स्वास्थ्य अंतर्दृष्टि के लिए उन्नत AI द्वारा संचालित",
    describe_symptoms: "अपने लक्षणों का वर्णन करें",
    send_message: "संदेश भेजें",
    ai_assistant_online: "AI सहायक ऑनलाइन",
    medical_disclaimer: "चिकित्सा अस्वीकरण",
    disclaimer_text:
      "यह AI सहायक केवल सामान्य स्वास्थ्य जानकारी प्रदान करता है और पेशेवर चिकित्सा सलाह का विकल्प नहीं है। आपातकाल के लिए, तुरंत आपातकालीन सेवाओं को कॉल करें। निदान और उपचार के लिए हमेशा स्वास्थ्य प्रदाताओं से सलाह लें।",
    immediate_help: "तत्काल सहायता और अस्पताल लोकेटर",
    health_education: "स्वास्थ्य शिक्षा",
    learn_health_topics: "स्वास्थ्य विषयों के बारे में जानें",
    register_for_more: "अधिक सुविधाओं के लिए रजिस्टर करें",
    get_personalized_insights: "व्यक्तिगत स्वास्थ्य अंतर्दृष्टि प्राप्त करें",
    unlock_features: "व्यक्तिगत स्वास्थ्य ट्रैकिंग, दवा अनुस्मारक, और अपने पूर्ण स्वास्थ्य डैशबोर्ड तक पहुंच अनलॉक करने के लिए रजिस्टर करें।",

    // Sample questions
    persistent_headache: "लगातार सिरदर्द",
    chest_discomfort: "सीने में बेचैनी",
    fever_body_aches: "बुखार और शरीर में दर्द",

    // Error messages
    access_denied: "पहुंच अस्वीकृत",
    login_required: "कृपया अपना डैशबोर्ड देखने के लिए लॉग इन करें",
    invalid_credentials: "अमान्य ईमेल या पासवर्ड। कृपया पुनः प्रयास करें।",
    user_exists: "इस ईमेल के साथ उपयोगकर्ता पहले से मौजूद है",
    password_mismatch: "पासवर्ड मेल नहीं खाते",
    password_length: "पासवर्ड कम से कम 6 अक्षर का होना चाहिए",
    required_field: "यह फील्ड आवश्यक है",

    // Success messages
    profile_updated: "प्रोफाइल सफलतापूर्वक अपडेट किया गया",
    registration_success: "पंजीकरण सफल! स्वास्थ्यAI में आपका स्वागत है।",
    login_success: "लॉगिन सफल! वापस स्वागत है।",

    // Emergency Page
    emergency_support_title: "आपातकालीन सहायता",
    immediate_help_desc: "जब आपको सबसे ज्यादा जरूरत हो तो तत्काल सहायता",
    emergency_numbers: "आपातकालीन नंबर",
    emergency_services: "आपातकालीन सेवाएं",
    all_emergency_services: "सभी आपातकालीन सेवाएं",
    ambulance: "एम्बुलेंस",
    medical_emergency: "चिकित्सा आपातकाल",
    fire_department: "दमकल विभाग",
    fire_emergency: "आग लगने की स्थिति में",
    police: "पुलिस",
    police_emergency: "पुलिस आपातकाल",
    disaster_management: "आपदा प्रबंधन",
    natural_disasters: "प्राकृतिक आपदाएँ",
    find_nearby_hospitals: "आस-पास के अस्पताल खोजें",
    locate_hospitals_desc: "निकटतम अस्पतालों का पता लगाएं और तुरंत दिशा-निर्देश प्राप्त करें",
    find_navigate_hospitals: "अस्पताल खोजें और नेविगेट करें",
    your_medical_information: "आपकी चिकित्सा जानकारी",
    name: "नाम",
    blood_group_info: "रक्त समूह",
    emergency_contact_info: "आपातकालीन संपर्क",
    first_aid_quick_reference: "प्राथमिक चिकित्सा त्वरित संदर्भ",
    cpr_full: "सीपीआर (कार्डियोपल्मोनरी रिससिटेशन)",
    choking: "गला घोंटना",
    severe_bleeding: "गंभीर रक्तस्राव",
    burns: "जलता है",
    fractures: "फ्रैक्चर",
    seizures: "दौरे",
    stroke_fast: "स्ट्रोक (फास्ट)",
    allergic_reactions: "एलर्जी प्रतिक्रियाएं",
    click_step_by_step: "चरण-दर-चरण मार्गदर्शिका के लिए क्लिक करें",
    back_to_all_guides: "← सभी गाइड पर वापस जाएं",
    important: "महत्वपूर्ण",
    remember_disclaimer:
      "याद रखें: ये बुनियादी प्राथमिक चिकित्सा दिशानिर्देश हैं। गंभीर चोटों के लिए या यदि आप स्थिति की गंभीरता के बारे में अनिश्चित हैं तो हमेशा आपातकालीन सेवाओं (112/108) को कॉल करें।",

    // Contact Page
    contact_us: "संपर्क करें",
    contact_desc: "हम यहां मदद करने के लिए हैं! किसी भी प्रश्न, समर्थन या सहयोग के अवसरों के लिए हमसे संपर्क करें।",
    get_in_touch: "संपर्क करें",
    phone: "फ़ोन",
    email: "ईमेल",
    address: "पता",
    support_hours: "समर्थन घंटे",
    emergency_support_24_7: "24/7 आपातकालीन सहायता",
    general_inquiries: "सामान्य पूछताछ: सुबह 9 बजे - शाम 6 बजे IST",
    our_response_time: "हमारी प्रतिक्रिया का समय",
    general: "सामान्य",
    send_us_message: "हमें एक संदेश भेजें",
    message_success: "आपके संदेश के लिए धन्यवाद! हम जल्द ही आपसे संपर्क करेंगे।",
    message_error: "क्षमा करें, आपका संदेश भेजने में त्रुटि हुई। कृपया पुन: प्रयास करें।",
    purpose: "उद्देश्य",
    select_purpose: "उद्देश्य चुनें",
    general_inquiry: "सामान्य पूछताछ",
    technical_support: "तकनीकी सहायता",
    medical_consultation: "चिकित्सा परामर्श",
    partnership_collaboration: "साझेदारी/सहयोग",
    feedback_suggestions: "प्रतिक्रिया/सुझाव",
    bug_report: "बग रिपोर्ट",
    message: "संदेश",
    message_placeholder: "कृपया अपनी पूछताछ या संदेश का विस्तार से वर्णन करें...",
    communication_consent: "मैं अपनी पूछताछ के संबंध में स्वास्थ्यAI से संचार प्राप्त करने के लिए सहमत हूं",
    sending: "भेजा जा रहा है...",
    send_message_btn: "संदेश भेजें",
    frequently_asked_questions: "अक्सर पूछे जाने वाले प्रश्न",
    ai_accuracy_question: "AI लक्षण जांचकर्ता कितना सटीक है?",
    ai_accuracy_answer:
      "हमारा AI व्यापक चिकित्सा डेटा पर प्रशिक्षित है और लक्षणों के आधार पर मार्गदर्शन प्रदान करता है, लेकिन इसे पेशेवर चिकित्सा सलाह का स्थान नहीं लेना चाहिए।",
    data_security_question: "क्या मेरा स्वास्थ्य डेटा सुरक्षित है?",
    data_security_answer:
      "हां, हम उद्योग-मानक एन्क्रिप्शन का उपयोग करते हैं और आपकी जानकारी को सुरक्षित रखने के लिए स्वास्थ्य सेवा डेटा सुरक्षा नियमों का पालन करते हैं।",
    book_appointments_question: "क्या मैं डॉक्टरों के साथ अपॉइंटमेंट बुक कर सकता हूं?",
    book_appointments_answer:
      "हां, हमारी मेडिकनेक्ट सुविधा के माध्यम से, आप सत्यापित स्वास्थ्य पेशेवरों के साथ वीडियो परामर्श शेड्यूल कर सकते हैं।",
    emergency_services_question: "क्या आप आपातकालीन सेवाएं प्रदान करते हैं?",
    emergency_services_answer:
      "हम अस्पताल लोकेटर और प्राथमिक चिकित्सा गाइड सहित आपातकालीन सहायता उपकरण प्रदान करते हैं, लेकिन तत्काल आपात स्थिति के लिए, 112 पर कॉल करें।",

    // Medications Page
    smart_medication_tracker: "स्मार्ट दवा ट्रैकर",
    medication_tracker_desc: "अपनी दवाओं के साथ ट्रैक पर रहें और स्वस्थ आदतें बनाएं",
    add_medication: "दवा जोड़ें",
    total_medications: "कुल दवाएं",
    taken_today: "आज ली गई",
    adherence_rate: "अनुपालन दर",
    longest_streak: "सबसे लंबी लकीर",
    todays_medications: "आज की दवाएं",
    dosage: "खुराक",
    frequency: "आवृत्ति",
    times: "बार",
    streak: "लकीर",
    days: "दिन",
    this_week: "इस सप्ताह",
    mark_taken: "चिह्नित लिया गया",
    completed: "पूर्ण",
    achievements: "उपलब्धियां",
    seven_day_streak: "7-दिवसीय लकीर",
    unlocked: "अनलॉक किया गया!",
    perfect_week: "परफेक्ट वीक",
    perfect_week_desc: "7 दिनों के लिए 100% अनुपालन",
    thirty_day_champion: "30-दिवसीय चैंपियन",
    days_to_go: "जाने के लिए दिन",
    upcoming_reminders: "आगामी अनुस्मारक",
    due_at: "पर देय",
    this_month: "इस महीने",
    days_100_adherence: "100% अनुपालन वाले दिन",
    missed_doses: "छूटी हुई खुराक",
    average_adherence: "औसत अनुपालन",
    add_new_medication: "नई दवा जोड़ें",
    medication_name: "दवा का नाम",
    medication_name_placeholder: "दवा का नाम दर्ज करें",
    dosage_placeholder: "जैसे, 500 मिलीग्राम, 1 टैबलेट",
    once_daily: "दिन में एक बार",
    twice_daily: "दिन में दो बार",
    three_times_daily: "दिन में तीन बार",
    as_needed: "आवश्यकतानुसार",
    instructions: "निर्देश",
    instructions_placeholder: "विशेष निर्देश...",

    // Additional keys for other pages (Hindi translations)
    expert_consultations: "विशेषज्ञ परामर्श",
    connect_with_doctors: "वीडियो कॉल, वॉयस कॉल, या टेक्स्ट चैट के माध्यम से तत्काल परामर्श के लिए सत्यापित स्वास्थ्य पेशेवरों से जुड़ें।",
    for_life_threatening: "जीवन-घातक आपातकाल के लिए",
    call_emergency: "तुरंत 112 या 108 पर कॉल करें। यह सेवा गैर-आपातकालीन परामर्श और चिकित्सा मार्गदर्शन के लिए है।",
    choose_healthcare_professional: "अपना स्वास्थ्य पेशेवर चुनें",
    experience: "अनुभव",
    rating: "रेटिंग",
    languages: "भाषाएं",
    available: "उपलब्ध",
    consultation_fee: "परामर्श शुल्क",
    continue_with: "के साथ जारी रखें",
    patient_information: "रोगी की जानकारी",
    patient_name: "रोगी का नाम",
    gender: "लिंग",
    select_gender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    consultation_type: "परामर्श प्रकार",
    video_call: "वीडियो कॉल",
    voice_call: "वॉयस कॉल",
    text_chat: "टेक्स्ट चैट",
    face_to_face_consultation: "वीडियो कॉल के माध्यम से आमने-सामने परामर्श",
    audio_consultation: "फोन कॉल पर ऑडियो परामर्श",
    text_based_consultation: "टेक्स्ट-आधारित परामर्श और मार्गदर्शन",
    urgency_level: "तात्कालिकता स्तर",
    normal_urgency: "सामान्य (24-48 घंटों के भीतर)",
    urgent: "तत्काल (2-4 घंटों के भीतर)",
    very_urgent: "अत्यंत तत्काल (1 घंटे के भीतर)",
    current_symptoms: "वर्तमान लक्षण / स्वास्थ्य चिंताएं",
    describe_symptoms_placeholder: "कृपया अपने लक्षण, चिंताएं, या परामर्श का कारण बताएं...",
    relevant_medical_history: "संबंधित चिकित्सा इतिहास",
    medical_history_placeholder: "कोई भी संबंधित चिकित्सा इतिहास, वर्तमान दवाएं, एलर्जी, आदि।",
    schedule_appointment: "अपॉइंटमेंट शेड्यूल करें",
    preferred_date: "पसंदीदा तारीख",
    preferred_time: "पसंदीदा समय",
    select_time: "समय चुनें",
    appointment_summary: "अपॉइंटमेंट सारांश",
    doctor: "डॉक्टर",
    specialty: "विशेषता",
    patient: "रोगी",
    urgency: "तात्कालिकता",
    terms_agreement:
      "मैं नियम और शर्तों से सहमत हूं और समझता हूं कि यह परामर्श शुल्क वापसी योग्य नहीं है। मैं गुणवत्ता और प्रशिक्षण उद्देश्यों के लिए इस सत्र की रिकॉर्डिंग के लिए भी सहमति देता हूं।",
    booking: "बुकिंग...",
    confirm_appointment: "अपॉइंटमेंट की पुष्टि करें",
    appointment_confirmed: "अपॉइंटमेंट की पुष्टि हो गई!",
    consultation_scheduled:
      "आपका परामर्श सफलतापूर्वक शेड्यूल हो गया है। आपको मीटिंग विवरण के साथ एक पुष्टिकरण ईमेल जल्द ही प्राप्त होगा।",
    date: "तारीख",
    time: "समय",
    type: "प्रकार",
    fee: "शुल्क",
    back_to_home: "होम पर वापस जाएं",

    // Education/MediAware Page
    health_education_hub: "स्वास्थ्य शिक्षा केंद्र",
    health_education_desc: "अपनी कल्याण यात्रा को सशक्त बनाने के लिए व्यापक स्वास्थ्य संसाधन, विशेषज्ञ लेख और शैक्षिक वीडियो देखें।",
    search_placeholder: "लेख, वीडियो और स्वास्थ्य विषयों खोजें...",
    all_content: "सभी सामग्री",
    articles_only: "केवल लेख",
    videos_only: "केवल वीडियो",
    all_categories: "सभी श्रेणियां",
    heart_health: "हृदय स्वास्थ्य",
    mental_health: "मानसिक स्वास्थ्य",
    prevention: "रोकथाम",
    fitness_nutrition: "फिटनेस और पोषण",
    emergency_care: "आपातकालीन देखभाल",
    chronic_diseases: "पुरानी बीमारियाँ",
    article: "लेख",
    video: "वीडियो",
    watch_video: "वीडियो देखें",
    no_content_found: "कोई सामग्री नहीं मिली",
    adjust_search_filters: "प्रासंगिक स्वास्थ्य सामग्री खोजने के लिए अपनी खोज शर्तों या फ़िल्टर को समायोजित करने का प्रयास करें।",
    need_personalized_guidance: "क्या आपको व्यक्तिगत स्वास्थ्य मार्गदर्शन की आवश्यकता है?",
    personalized_guidance_desc: "हमारे AI-संचालित लक्षण जांचकर्ता से जुड़ें या स्वास्थ्य विशेषज्ञों के साथ परामर्श बुक करें।",
    try_symptom_checker: "लक्षण जांचकर्ता आज़माएं",
    book_consultation: "परामर्श बुक करें",

    // Profile Page
    personal_information: "व्यक्तिगत जानकारी",
    medical_information: "चिकित्सा जानकारी",
    no_medical_conditions: "कोई चिकित्सा स्थिति नहीं बताई गई",
    privacy_security: "गोपनीयता और सुरक्षा",
    two_factor_auth: "दो-कारक प्रमाणीकरण",
    two_factor_desc: "अपने खाते में सुरक्षा की एक अतिरिक्त परत जोड़ें",
    enable: "सक्षम करें",
    data_export: "डेटा निर्यात",
    data_export_desc: "अपने स्वास्थ्य डेटा की एक प्रति डाउनलोड करें",
    export: "निर्यात",
    delete_account: "खाता हटाएं",
    delete_account_desc: "स्थायी रूप से अपना खाता और सभी डेटा हटाएं",
    delete: "हटाएं",

    // MediCollab Page
    partner_with_us: "हमारे साथ साझेदारी करें",
    collaboration_mission_desc:
      "सभी के लिए गुणवत्तापूर्ण स्वास्थ्य सेवा सुलभ बनाने के हमारे मिशन में शामिल हों। मिलकर, हम सहयोग, नवाचार और कल्याण के लिए साझा प्रतिबद्धता के माध्यम से एक स्वस्थ भारत बना सकते हैं।",
    our_collaboration_mission: "हमारा सहयोग मिशन",
    collaboration_mission_text:
      "स्वास्थ्यAI स्वास्थ्य सेवा वितरण को बदलने के लिए साझेदारी की शक्ति में विश्वास करता है। हम एक ऐसा पारिस्थितिकी तंत्र बना रहे हैं जहां प्रौद्योगिकी, विशेषज्ञता और करुणा मिलकर भारत भर के समुदायों की सेवा करते हैं।",
    community_impact: "सामुदायिक प्रभाव",
    community_impact_desc: "गुणवत्तापूर्ण स्वास्थ्य सेवा के साथ वंचित समुदायों तक पहुंचना",
    shared_values: "साझा मूल्य",
    shared_values_desc: "सुलभ, किफायती और गुणवत्तापूर्ण स्वास्थ्य सेवा के लिए प्रतिबद्धता",
    mutual_growth: "पारस्परिक विकास",
    mutual_growth_desc: "स्वास्थ्य सेवा पारिस्थितिकी तंत्र में सभी हितधारकों के लिए मूल्य सृजन",
    collaboration_opportunities: "सहयोग के अवसर",
    ngos_nonprofits: "एनजीओ और गैर-लाभकारी संस्थाएं",
    ngo_description: "स्वास्थ्य शिविर, रक्तदान अभियान और सामुदायिक कल्याण कार्यक्रम आयोजित करने के लिए हमारे साथ साझेदारी करें।",
    individual_ambassadors: "व्यक्तिगत राजदूत",
    ambassador_description: "अपने समुदाय में स्वास्थ्यAI राजदूत बनें और स्वास्थ्य जागरूकता फैलाने में मदद करें।",
    hospitals_clinics: "अस्पताल और क्लिनिक",
    hospital_description: "गुणवत्तापूर्ण स्वास्थ्य सेवाएं प्रदान करने और अधिक रोगियों तक पहुंचने के लिए हमारे नेटवर्क में शामिल हों।",
    healthcare_professionals: "स्वास्थ्य पेशेवर",
    doctor_description: "विशेषज्ञ चिकित्सा मार्गदर्शन प्रदान करने और अपनी प्रैक्टिस का विस्तार करने के लिए हमारे साथ सहयोग करें।",
    corporate_partners: "कॉर्पोरेट साझेदार",
    corporate_description: "कर्मचारी कल्याण कार्यक्रमों और कॉर्पोरेट सामाजिक जिम्मेदारी पहलों के लिए हमारे साथ साझेदारी करें।",
    academic_institutions: "शैक्षणिक संस्थान",
    academic_description: "स्वास्थ्य ज्ञान को आगे बढ़ाने के लिए अनुसंधान, शिक्षा और प्रशिक्षण कार्यक्रमों पर सहयोग करें।",
    collaboration_opportunities_list: "सहयोग के अवसर:",
    benefits_recognition: "लाभ और मान्यता:",
    success_stories: "सफलता की कहानियां",
    rural_health_initiative: "ग्रामीण स्वास्थ्य पहल",
    rural_health_desc:
      "15 एनजीओ के साथ साझेदारी करके 50+ गांवों में स्वास्थ्य शिविर आयोजित किए, 10,000+ लोगों की जांच की और मुफ्त दवाएं प्रदान कीं।",
    people_served: "लोगों की सेवा की गई",
    ambassador_network: "राजदूत नेटवर्क",
    ambassador_network_desc:
      "200+ सामुदायिक राजदूतों को प्रशिक्षित किया जिन्होंने 25,000+ व्यक्तियों तक पहुंचने वाले स्वास्थ्य जागरूकता सत्र आयोजित किए।",
    active_ambassadors: "सक्रिय राजदूत",
    hospital_network: "अस्पताल नेटवर्क",
    hospital_network_desc: "100+ अस्पतालों और क्लीनिकों को हमारे प्लेटफॉर्म से जोड़ा, 50,000+ टेलीमेडिसिन परामर्श सक्षम किए।",
    partner_hospitals: "साझेदार अस्पताल",
    ready_to_collaborate: "सहयोग के लिए तैयार हैं?",
    partnership_form_desc: "नीचे दिया गया फॉर्म भरें और हमारी साझेदारी टीम 48 घंटों के भीतर आपसे संपर्क करेगी।",
    organization_representative: "पूरा नाम / संगठन प्रतिनिधि",
    organization_name: "संगठन का नाम",
    organization_placeholder: "संगठन का नाम दर्ज करें (यदि लागू हो)",
    collaboration_category: "सहयोग श्रेणी",
    select_category: "श्रेणी चुनें",
    ngo_nonprofit: "एनजीओ / गैर-लाभकारी",
    individual_ambassador: "व्यक्तिगत राजदूत",
    hospital_clinic: "अस्पताल / क्लिनिक",
    healthcare_professional: "स्वास्थ्य पेशेवर",
    corporate_partner: "कॉर्पोरेट साझेदार",
    academic_institution: "शैक्षणिक संस्थान",
    location_city_state: "स्थान (शहर, राज्य)",
    relevant_experience: "संबंधित अनुभव / पृष्ठभूमि",
    experience_placeholder: "अपने संबंधित अनुभव या पृष्ठभूमि का संक्षेप में वर्णन करें...",
    collaboration_ideas: "आप हमारे साथ कैसे सहयोग करना चाहेंगे?",
    collaboration_placeholder: "कृपया अपने सहयोग विचार, लक्ष्यों और आप हमारे मिशन में कैसे योगदान कर सकते हैं, इसका वर्णन करें...",
    consent_agreement:
      "मैं सहयोग के अवसरों के बारे में स्वास्थ्यAI से संचार प्राप्त करने के लिए सहमत हूं और समझता हूं कि मेरी जानकारी का उपयोग गोपनीयता नीति के अनुसार किया जाएगा।",
    submitting: "प्रस्तुत किया जा रहा है...",
    submit_collaboration_request: "सहयोग अनुरोध सबमिट करें",
    have_questions: "कोई प्रश्न हैं?",
    partnership_team_help: "हमारी साझेदारी टीम सहयोग के अवसरों का पता लगाने में आपकी मदद करने के लिए यहां है।",
   
    // Stats
    happy_users: "खुश उपयोगकर्ता",
    healthcare_partners: "स्वास्थ्य सेवा भागीदार",
    support_available: "24/7 सहायता उपलब्ध",
    uptime: "अपटाइम",

    // Testimonials
    software_engineer: "सॉफ्टवेयर इंजीनियर",
    general_physician: "सामान्य चिकित्सक",
    teacher: "शिक्षक",
    testimonial_priya: "SwasthyaAI ने मुझे अपने लक्षणों को समझने और सही डॉक्टर से जुड़ने में मदद की। एआई निदान अविश्वसनीय रूप से सटीक था!",
    testimonial_rajesh: "एक स्वास्थ्य पेशेवर के रूप में, मैं सराहना करता हूं कि मेडिसेंस रोगियों को कैसे शिक्षित करता है और उन्हें अपने स्वास्थ्य के बारे में सूचित निर्णय लेने में मदद करता है।",
    testimonial_amit: "आपातकालीन सुविधाओं ने मेरे पिता की जान बचाई। पास के अस्पतालों और प्राथमिक चिकित्सा जानकारी तक त्वरित पहुंच अमूल्य है।",

    // Platform Description
    platform_description: "हमारा एआई-संचालित प्लेटफॉर्म अत्याधुनिक प्रौद्योगिकी को मानव विशेषज्ञता के साथ जोड़कर व्यापक स्वास्थ्य सेवा सहायता प्रदान करता है।",

    // How It Works
    how_it_works: "SwasthyaAI कैसे काम करता है",
    simple_steps: "बेहतर स्वास्थ्य प्रबंधन के लिए सरल कदम",
    describe_symptoms_step: "अपने लक्षणों का वर्णन करें",
    describe_symptoms_desc: "प्राकृतिक भाषा में हमारे एआई को अपनी स्वास्थ्य चिंताओं के बारे में बताएं",
    get_ai_analysis: "एआई विश्लेषण प्राप्त करें",
    get_ai_analysis_desc: "व्यक्तिगत स्वास्थ्य अंतर्दृष्टि और सिफारिशें प्राप्त करें",
    connect_with_experts: "विशेषज्ञों से जुड़ें",
    connect_with_experts_desc: "जरूरत पड़ने पर स्वास्थ्य पेशेवरों से जुड़ें",

    // Testimonials Section
    what_users_say: "हमारे उपयोगकर्ता क्या कहते हैं",
    trusted_by_users: "भारत भर में हजारों उपयोगकर्ताओं द्वारा विश्वसनीय",

    // CTA Section
    ready_to_transform: "अपनी स्वास्थ्य यात्रा को बदलने के लिए तैयार हैं?",
    join_thousands: "हजारों उपयोगकर्ताओं में शामिल हों जो अपनी स्वास्थ्य सेवा आवश्यकताओं के लिए SwasthyaAI पर भरोसा करते हैं",
  
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<"en" | "hi">("en")

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "hi" : "en"))
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}